[package]
name = "input"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
protocol.workspace = true
enigo.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
