use std::net::{Ipv4Addr, SocketAddrV4};

use rand::Rng;

use crate::verify_code;

/// Crockford base32 alphabet: no I, L, O, U, so a code can be read aloud and
/// typed back without ambiguity (`O` decodes as `0`, `I`/`L` as `1`).
const ALPHABET: &[u8; 32] = b"0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/// 16 base32 characters carry the whole 80-bit payload.
const CODE_CHARS: usize = 16;
const GROUP_LEN: usize = 4;

/// LAN payload layout, most significant bits first:
/// version (2 bits) | secret (30 bits) | IPv4 (32 bits) | port (16 bits).
const LAN_VERSION: u128 = 0;
/// Internet/rendezvous payload layout, most significant bits first:
/// version (2 bits) | secret (30 bits) | rendezvous id (48 bits).
const RENDEZVOUS_VERSION: u128 = 1;
const SECRET_BITS: u32 = 30;
const RENDEZVOUS_ID_BITS: u32 = 48;
const RENDEZVOUS_ID_MASK: u64 = (1u64 << RENDEZVOUS_ID_BITS) - 1;

/// The endpoint encoded by an access code.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConnectTarget {
    Lan(SocketAddrV4),
    Rendezvous { id: u64 },
}

/// A self-contained access code: the host's address plus a single-use secret,
/// encoded as one string the user can dictate (`XXXX-XXXX-XXXX-XXXX`).
///
/// The wire authentication still sends the full code string; the host compares
/// it in constant time. The embedded address only spares the viewer from typing
/// `IP:port` separately — it is not a secret by itself.
#[derive(Clone)]
pub struct ConnectCode {
    target: ConnectTarget,
    /// Canonical display form, grouped with hyphens.
    code: String,
}

/// Why a typed access code could not be decoded.
#[derive(Debug, PartialEq, Eq, thiserror::Error)]
pub enum ConnectCodeError {
    #[error("access code must have {CODE_CHARS} characters")]
    WrongLength,
    #[error("access code contains an invalid character")]
    InvalidChar,
    #[error("access code was generated by a newer version")]
    UnsupportedVersion,
    #[error("rendezvous id must fit in {RENDEZVOUS_ID_BITS} bits")]
    RendezvousIdOutOfRange,
}

impl ConnectCode {
    /// Generates a fresh code for the given host address with a random secret.
    pub fn generate(addr: SocketAddrV4) -> Self {
        let secret: u32 = rand::thread_rng().gen_range(0..1u32 << SECRET_BITS);
        Self::assemble_lan(addr, secret)
    }

    /// Generates a fresh internet code for a rendezvous registration id.
    pub fn generate_rendezvous(id: u64) -> Result<Self, ConnectCodeError> {
        if id > RENDEZVOUS_ID_MASK {
            return Err(ConnectCodeError::RendezvousIdOutOfRange);
        }
        let secret: u32 = rand::thread_rng().gen_range(0..1u32 << SECRET_BITS);
        Ok(Self::assemble_rendezvous(id, secret))
    }

    /// Decodes a code typed by the user, tolerating case, separators and the
    /// classic o/0 and i/l/1 confusions.
    pub fn parse(input: &str) -> Result<Self, ConnectCodeError> {
        let digits = normalize(input)?;
        if digits.len() != CODE_CHARS {
            return Err(ConnectCodeError::WrongLength);
        }
        let mut value: u128 = 0;
        for digit in digits {
            value = (value << 5) | digit as u128;
        }
        let version = value >> 78;
        let secret = ((value >> 48) & ((1 << SECRET_BITS) - 1)) as u32;
        match version {
            LAN_VERSION => {
                let ip = Ipv4Addr::from(((value >> 16) & 0xFFFF_FFFF) as u32);
                let port = (value & 0xFFFF) as u16;
                Ok(Self::assemble_lan(SocketAddrV4::new(ip, port), secret))
            }
            RENDEZVOUS_VERSION => {
                let id = (value & RENDEZVOUS_ID_MASK as u128) as u64;
                Ok(Self::assemble_rendezvous(id, secret))
            }
            _ => Err(ConnectCodeError::UnsupportedVersion),
        }
    }

    /// The endpoint embedded in the code.
    pub fn target(&self) -> ConnectTarget {
        self.target
    }

    /// The LAN host address embedded in a v0 code.
    pub fn addr(&self) -> Option<SocketAddrV4> {
        match self.target {
            ConnectTarget::Lan(addr) => Some(addr),
            ConnectTarget::Rendezvous { .. } => None,
        }
    }

    /// Canonical display form (`XXXX-XXXX-XXXX-XXXX`).
    pub fn as_str(&self) -> &str {
        &self.code
    }

    /// Checks a candidate typed on the viewer against this code in constant
    /// time (after normalization, so `o`/`0`, `i`/`l`/`1`, case and separators
    /// do not cause false rejections).
    pub fn verify(&self, candidate: &str) -> bool {
        let Ok(normalized) = ConnectCode::parse(candidate) else {
            // Not decodable as a code: fall back to a plain normalized compare
            // so the attempt is still counted uniformly by the caller.
            return verify_code(&self.code, candidate);
        };
        verify_code(&self.code, normalized.as_str())
    }

    fn assemble_lan(addr: SocketAddrV4, secret: u32) -> Self {
        let value: u128 = (LAN_VERSION << 78)
            | ((secret as u128) << 48)
            | ((u32::from(*addr.ip()) as u128) << 16)
            | addr.port() as u128;
        Self::from_payload(ConnectTarget::Lan(addr), value)
    }

    fn assemble_rendezvous(id: u64, secret: u32) -> Self {
        let value: u128 = (RENDEZVOUS_VERSION << 78) | ((secret as u128) << 48) | id as u128;
        Self::from_payload(ConnectTarget::Rendezvous { id }, value)
    }

    fn from_payload(target: ConnectTarget, value: u128) -> Self {
        let mut chars = Vec::with_capacity(CODE_CHARS + CODE_CHARS / GROUP_LEN - 1);
        for i in (0..CODE_CHARS).rev() {
            if !chars.is_empty() && (CODE_CHARS - i) % GROUP_LEN == 1 && i != CODE_CHARS - 1 {
                chars.push(b'-');
            }
            chars.push(ALPHABET[((value >> (i * 5)) & 0x1F) as usize]);
        }
        Self {
            target,
            code: String::from_utf8(chars).expect("alphabet is ASCII"),
        }
    }
}

impl std::fmt::Debug for ConnectCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // The code contains the session secret: never print it in logs.
        write!(f, "ConnectCode({:?}, ***)", self.target)
    }
}

/// Uppercases, drops separators, maps Crockford aliases and converts each
/// character to its 5-bit value.
fn normalize(input: &str) -> Result<Vec<u8>, ConnectCodeError> {
    let mut digits = Vec::with_capacity(CODE_CHARS);
    for c in input.chars() {
        if c.is_whitespace() || c == '-' || c == '_' {
            continue;
        }
        let c = match c.to_ascii_uppercase() {
            'O' => '0',
            'I' | 'L' => '1',
            other => other,
        };
        let Some(digit) = ALPHABET.iter().position(|&a| a as char == c) else {
            return Err(ConnectCodeError::InvalidChar);
        };
        if digits.len() == CODE_CHARS {
            return Err(ConnectCodeError::WrongLength);
        }
        digits.push(digit as u8);
    }
    Ok(digits)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn addr(a: [u8; 4], port: u16) -> SocketAddrV4 {
        SocketAddrV4::new(Ipv4Addr::new(a[0], a[1], a[2], a[3]), port)
    }

    #[test]
    fn roundtrips_address_and_secret() {
        let code = ConnectCode::generate(addr([192, 168, 0, 10], 21118));
        let parsed = ConnectCode::parse(code.as_str()).unwrap();
        assert_eq!(parsed.addr(), code.addr());
        assert!(matches!(parsed.target(), ConnectTarget::Lan(_)));
        assert_eq!(parsed.as_str(), code.as_str());
    }

    #[test]
    fn roundtrips_rendezvous_id_and_secret() {
        let code = ConnectCode::generate_rendezvous(0x1234_5678_9abc).unwrap();
        let parsed = ConnectCode::parse(code.as_str()).unwrap();
        assert_eq!(
            parsed.target(),
            ConnectTarget::Rendezvous {
                id: 0x1234_5678_9abc
            }
        );
        assert_eq!(parsed.addr(), None);
        assert_eq!(parsed.as_str(), code.as_str());
    }

    #[test]
    fn rejects_rendezvous_id_outside_48_bits() {
        assert!(matches!(
            ConnectCode::generate_rendezvous(1u64 << 48),
            Err(ConnectCodeError::RendezvousIdOutOfRange)
        ));
    }

    #[test]
    fn display_form_is_grouped() {
        let code = ConnectCode::generate(addr([10, 0, 0, 1], 1));
        let s = code.as_str();
        assert_eq!(s.len(), CODE_CHARS + 3);
        assert!(s.split('-').all(|g| g.len() == GROUP_LEN));
    }

    #[test]
    fn parse_tolerates_case_separators_and_aliases() {
        let code = ConnectCode::generate(addr([172, 16, 5, 77], 21118));
        let lax: String = code
            .as_str()
            .chars()
            .filter(|c| *c != '-')
            .map(|c| match c {
                '0' => 'o',
                '1' => 'l',
                other => other.to_ascii_lowercase(),
            })
            .collect();
        let parsed = ConnectCode::parse(&lax).unwrap();
        assert_eq!(parsed.as_str(), code.as_str());
        assert!(code.verify(&lax));
    }

    #[test]
    fn rejects_bad_input() {
        assert!(matches!(
            ConnectCode::parse("2345-6789"),
            Err(ConnectCodeError::WrongLength)
        ));
        assert!(matches!(
            ConnectCode::parse(""),
            Err(ConnectCodeError::WrongLength)
        ));
        assert!(matches!(
            ConnectCode::parse("XXXX-XXXX-XXXX-XXX!"),
            Err(ConnectCodeError::InvalidChar)
        ));
        // 16 valid chars but with the top version bits set.
        let future = "Z".repeat(16);
        assert!(matches!(
            ConnectCode::parse(&future),
            Err(ConnectCodeError::UnsupportedVersion)
        ));
    }

    #[test]
    fn verify_rejects_wrong_secret() {
        let code = ConnectCode::generate(addr([192, 168, 1, 2], 21118));
        let mut tampered: String = code.as_str().into();
        // Flip one secret character (first group carries version+secret bits).
        let first = tampered.remove(1);
        let replacement = if first == '2' { '3' } else { '2' };
        tampered.insert(1, replacement);
        assert!(!code.verify(&tampered));
    }

    #[test]
    fn generated_codes_differ() {
        let a = ConnectCode::generate(addr([192, 168, 1, 2], 21118));
        let b = ConnectCode::generate(addr([192, 168, 1, 2], 21118));
        assert_ne!(a.as_str(), b.as_str());
    }

    #[test]
    fn debug_hides_the_secret() {
        let code = ConnectCode::generate(addr([192, 168, 1, 2], 21118));
        let debug = format!("{code:?}");
        assert!(!debug.contains(code.as_str()));
        assert!(debug.contains("***"));
    }
}
